/**
 * Capture filter chain: decides whether a clipboard payload is skipped entirely,
 * stored-but-flagged-secret (masked, never indexed/enriched/embedded), or stored normally.
 */

export type FilterVerdict = 'store' | 'store-secret' | 'skip'

/** Clipboard formats that password managers use to mark sensitive/transient content. */
const CONCEALED_FORMATS = [
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.TransientType',
  'org.nspasteboard.AutoGeneratedType',
  'x-kde-passwordManagerHint',
  'application/x-kde-passwordManagerHint'
]

const SECRET_PATTERNS: Array<{ name: string; re: RegExp }> = [
  { name: 'aws-access-key', re: /\b(AKIA|ASIA|ABIA|ACCA)[0-9A-Z]{16}\b/ },
  { name: 'aws-secret-key', re: /\baws_secret_access_key\s*[=:]\s*\S{30,}/i },
  { name: 'private-key-block', re: /-----BEGIN (?:RSA |EC |OPENSSH |PGP )?PRIVATE KEY/ },
  { name: 'jwt', re: /\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b/ },
  { name: 'github-token', re: /\bgh[pousr]_[A-Za-z0-9]{36,}\b/ },
  { name: 'openai-key', re: /\bsk-[A-Za-z0-9_-]{20,}\b/ },
  { name: 'anthropic-key', re: /\bsk-ant-[A-Za-z0-9_-]{20,}\b/ },
  { name: 'google-api-key', re: /\bAIza[0-9A-Za-z_-]{35}\b/ },
  { name: 'slack-token', re: /\bxox[baprs]-[A-Za-z0-9-]{10,}\b/ },
  { name: 'stripe-key', re: /\b[sr]k_(live|test)_[A-Za-z0-9]{20,}\b/ },
  { name: 'generic-assignment', re: /\b(password|passwd|secret|api[_-]?key|token)\s*[=:]\s*["']?[^\s"']{12,}/i },
  { name: 'connection-string-cred', re: /\b\w+:\/\/[^\s:@/]+:[^\s:@/]{6,}@[^\s@]+/ }
]

/** Shannon entropy per char; random key material scores > ~4.2, prose ~2.5–3.5. */
function entropy(s: string): number {
  const freq = new Map<string, number>()
  for (const c of s) freq.set(c, (freq.get(c) ?? 0) + 1)
  let h = 0
  for (const n of freq.values()) {
    const p = n / s.length
    h -= p * Math.log2(p)
  }
  return h
}

/**
 * A lone high-entropy token with no spaces smells like key material — but plenty of
 * ordinary things are long, spaceless and mixed-case. Everything excluded here is a
 * false positive we've actually seen; a wrongly-flagged clip is invisible to search
 * and enrichment, so precision matters as much as recall.
 */
function looksLikeLoneSecret(text: string): boolean {
  const t = text.trim()
  if (t.length < 20 || t.length > 512) return false
  if (/\s/.test(t)) return false
  if (/^[a-z][a-z0-9+.-]*:\/\//i.test(t)) return false // any URL scheme
  if (/^~?\.{0,2}\//.test(t) || (t.match(/\//g)?.length ?? 0) >= 2) return false // filesystem paths
  if (/^[A-Za-z]:\\/.test(t) || t.includes('\\')) return false // Windows paths
  if (/\.[a-z0-9]{1,5}$/i.test(t) && (t.includes('/') || t.includes('.'))) {
    // Looks like a filename or a dotted identifier (com.example.Thing, file.tar.gz).
    if (!/[^A-Za-z0-9._/-]/.test(t)) return false
  }
  // Require mixed char classes so hashes-you-meant-to-copy (hex SHAs) don't trip it.
  const classes =
    Number(/[a-z]/.test(t)) + Number(/[A-Z]/.test(t)) + Number(/\d/.test(t)) + Number(/[^A-Za-z0-9]/.test(t))
  return classes >= 3 && entropy(t) > 4.0
}

export function detectSecret(text: string): string | null {
  for (const { name, re } of SECRET_PATTERNS) {
    if (re.test(text)) return name
  }
  if (looksLikeLoneSecret(text)) return 'high-entropy-token'
  return null
}

export function hasConcealedFormat(formats: string[]): boolean {
  const lower = formats.map((f) => f.toLowerCase())
  return CONCEALED_FORMATS.some((c) => lower.includes(c.toLowerCase()))
}

export interface FilterInput {
  text?: string
  formats: string[]
  sourceApp?: string
  /**
   * macOS bundle id of the source app, when known. Matched alongside the display
   * name because the two disagree in exactly the cases that matter: 1Password's
   * browser extension helper reports names like "1Password Extension Helper" but a
   * stable `com.1password.*` id, and a localized app name may not contain the
   * English substring the user put in their ignore list at all.
   */
  sourceAppId?: string
  /**
   * Windows' concealed-content markers, reported out of band by the clipboard
   * sidecar (src/main/win/sequenceWatcher.ts).
   *
   * A separate input rather than three more names in `formats`, because
   * `clipboard.availableFormats()` will NEVER list them: they are registered formats
   * with no MIME mapping, so Chromium does not report them at all. Stuffing invented
   * names into the formats array would make the filter pass while the thing it
   * describes was never actually observed — a defence that tests green and does
   * nothing.
   */
  concealedWin?: boolean
  ignoreApps: string[]
}

export function runFilters(input: FilterInput): { verdict: FilterVerdict; reason?: string } {
  if (hasConcealedFormat(input.formats)) return { verdict: 'skip', reason: 'concealed-format' }
  if (input.concealedWin) return { verdict: 'skip', reason: 'concealed-format' }

  const haystacks = [input.sourceApp, input.sourceAppId]
    .filter((s): s is string => !!s)
    .map((s) => s.toLowerCase())
  if (haystacks.length > 0) {
    const needle = input.ignoreApps.find((a) => {
      const lower = a.toLowerCase()
      return haystacks.some((h) => h.includes(lower))
    })
    if (needle) return { verdict: 'skip', reason: `ignored-app:${input.sourceApp ?? input.sourceAppId}` }
  }

  if (input.text) {
    if (input.text.trim().length === 0) return { verdict: 'skip', reason: 'empty' }
    const secret = detectSecret(input.text)
    if (secret) return { verdict: 'store-secret', reason: secret }
  }

  return { verdict: 'store' }
}
